package_name: Trnasformer
save_file: "./test_dir"

TR_model:
  src_vocab_size : 1024
  tgt_vocab_size : 100
  src_seq_len : 350
  tgt_seq_len : 500
  seq_len : 350
  lang_src: "en"
  lang_tgt: "it"
  d_model : 512
  num_layer : 6
  num_heads : 8
  dropout: 0.0
  d_ff: 2048
  lr: 0.0001
  batch_size: 16
  epochs: 20
  ckpt_file: None
  tokenizer_file: "tokenizer_{}.json"