TR_model:
  batch_size: 16
  ckpt_file: None
  d_ff: 256
  d_model: 512
  dropout: 0.0
  epochs: 20
  lang_src: en
  lang_tgt: it
  lr: 0.0001
  num_layer: 0
  num_neads: 8
  seq_len: 350
  src_seq_len: 350
  src_vocab_size: 1024
  tgt_seq_len: 500
  tgt_vocab_size: 100
  tokenizer_file: tokenizer_{0}.json
